import { test, expect } from '@playwright/test';
test('offline nutrient balance options, goal switch and saved snapshot', async ({page,context})=>{
  await page.goto('/');
  await page.getByRole('button',{name:'Continue',exact:false}).click();
  await page.evaluate(async()=>{await navigator.serviceWorker.ready;});
  await page.reload();
  await context.setOffline(true);
  await page.getByRole('navigation').getByRole('button',{name:'New feed test'}).click();
  await page.getByRole('button',{name:'Next'}).click();
  await page.getByRole('button',{name:'Yes, continue'}).click();
  await page.getByLabel('Who is this feed for? (optional)').selectOption('lactating');
  await page.getByText('Optional lab or feed-label values',{exact:true}).click();
  await page.getByRole('spinbutton',{name:'Crude protein',exact:true}).fill('8');
  await page.getByRole('spinbutton',{name:'Fiber (NDF)',exact:true}).fill('20');
  await page.getByLabel('I have ingredient targets from my nutritionist').check();
  await page.getByLabel('Target reference / nutritionist').fill('Test-only ingredient benchmark');
  await page.getByLabel('Protein minimum (% DM)').fill('12');
  await page.getByLabel('NDF minimum (% DM)').fill('30');
  await page.getByRole('button',{name:'Next'}).click();
  await page.getByRole('button',{name:'Milk Production',exact:true}).click();
  await page.getByRole('button',{name:'Next'}).click();
  await page.getByRole('combobox',{name:'Reading source',exact:true}).selectOption('virtual');
  await page.getByRole('button',{name:'Low indicated risk',exact:true}).click();
  await page.getByRole('button',{name:'Check feed'}).click();
  const balance=page.getByRole('region',{name:'Nutrient balance',exact:true});
  await expect(balance).toBeVisible();
  // Four grid rings plus two real comparable values; missing axes get no dot.
  await expect(page.locator('.radar-chart circle')).toHaveCount(6);
  await balance.getByRole('button',{name:'Protein-rich feed category',exact:true}).click();
  await expect(balance.getByRole('table')).toContainText('May support this nutrient');
  await expect(balance).toContainText('not a predicted after-feeding composition');
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await balance.screenshot({path:'test-results/nutrient-balance-mobile.png'});
  await page.locator('.goal-summary').getByText('Change goal',{exact:true}).click();
  await page.locator('.goal-summary').getByRole('button',{name:'Animal Health',exact:true}).click();
  await expect(balance.getByRole('button').first()).toContainText('Fiber');
  await page.getByRole('button',{name:'Save batch test',exact:true}).click();
  await expect(page.getByRole('button',{name:'Saved on this device',exact:true})).toBeVisible();
});
